language: go

sudo: required

services:
  - docker

script:
  - docker build -t chrome27 .

branches:
  only:
  - master

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag chrome27 gustajz/chrome27
  - docker push gustajz/chrome27:latest